name: chao
channels:
  - defaults
dependencies:
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.11.4=haa95532_0
  - expat=2.7.3=h9214b88_0
  - libffi=3.4.4=hd77b12b_1
  - libzlib=1.3.1=h02ab6af_0
  - openssl=3.0.18=h543e019_0
  - pip=25.3=pyhc872135_0
  - python=3.12.4=h14ffc60_1
  - setuptools=80.9.0=py312haa95532_0
  - sqlite=3.51.0=hda9a48d_0
  - tk=8.6.15=hf199647_0
  - ucrt=10.0.22621.0=haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wheel=0.45.1=py312haa95532_0
  - xz=5.6.4=h4754444_1
  - zlib=1.3.1=h02ab6af_0
  - pip:
      - asgiref==3.11.0
      - cffi==2.0.0
      - cryptography==46.0.3
      - django==4.2.26
      - django-ckeditor==6.7.3
      - django-cors-headers==4.9.0
      - django-filter==25.1
      - django-js-asset==3.1.2
      - django-redis==6.0.0
      - django-simpleui==2025.6.24
      - djangorestframework==3.16.1
      - djangorestframework-simplejwt==5.5.1
      - pillow==12.0.0
      - pycparser==2.23
      - pyjwt==2.10.1
      - pymysql==1.1.2
      - python-decouple==3.8
      - redis==7.1.0
      - sqlparse==0.5.4
      - tzdata==2025.2
prefix: F:\Anaconda2024\3\envs\chao
